[package]
name = "typst-yuepu"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "lib.typ"
authors = ["Shuenhoy"]
license = "MIT"
description = "Rendering music sheet with abc2svg"

repository = "https://github.com/Shuenhoy/typst-yuepu"

keywords = ["javascript", "sheet", "music", "abcnotation"]
